name: Signalkuppe
slogan: Parole oltre i 4000m
description: Blog personale di Matteo Leoni
url: http://www.signalkuppe.com
markdown: redcarpet
pygments: true
baseurl: /
exclude: [bower.json, .bowerrc, README, s3_website.yml]