# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Signalkuppe
slogan: "Parole oltre i 4000m"
email: leoni.matteo@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Blog personale di Matteo Leoni
baseurl: "" # the subpath of your site, e.g. /blog
lang: "it"
url: "http://www.signalkuppe.com" # the base hostname & protocol for your site, e.g. http://example.com
fullurl: "http://www.signalkuppe.com" # the base hostname & protocol for your site, e.g. http://example.com
flickr:
 cache_dir:       "./_cache"
 api_key: ENV_FLICKR_API_KEY
 shared_secret: ENV_FLICKR_SHARED_SECRET
 access_token: ENV_FLICKR_ACCESS_TOKEN
 access_secret: ENV_FLICKR_ACCESS_SECRET
sitemap:
    file: "/sitemap.xml"
    exclude:
       "/404.html"
    change_frequency_name: "change_frequency"
    priority_name: "priority"

# Build settings
markdown: kramdown

plugins:
  - jekyll-sitemap

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
